[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

repositories {
  maven { url 'https://jitpack.io' }
}

dependencies {
  api "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api 'com.github.crykn:kryonet:2.22.9'
  testImplementation "junit:junit:4.13.2"
  testImplementation "com.badlogicgames.gdx:gdx-backend-headless:1.13.5"
  runtimeOnly "com.badlogicgames.gdx:gdx-platform:1.10.0:natives-desktop"
  
  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}
